version: '2'

services:
  mysql:
    container_name: "MySQL"
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./server/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  adminer:
    container_name: "Adminer"
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - mysql

  nginx:
    container_name: "Nginx"
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-images/nginx/server.conf:/etc/nginx/conf.d/server.conf
      - ./docker-images/nginx/client-proxy.conf:/etc/nginx/conf.d/client.conf
      - ./server/www:/var/server
      - ./server/logs:/var/log/nginx/server
    links:
      - php
      - node
  php:
    container_name: "PHP-FPM"
    restart: always
    build: docker/php-dev
    links:
      - mysql
    volumes:
      - ./server/www:/var/server
    ports:
      - 10000
    env_file:
      - .env

  node:
    restart: "on-failure"
    container_name: "NodeJS"
    image: "node:10"
    user: "$DOCKER_USER"
    working_dir: /home/node/client
    environment:
      NODE_ENV: "development"
    volumes:
      - ./client:/home/node/client
    ports:
      - "8081:8081"
    command: >
      bash -c "npm install
      && npm run serve"