version: '3'

services:
  redis:
    restart: always
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DISABLE_COMMANDS: ${REDIS_DISABLE_COMMANDS}

  client:
    restart: always
    image: "node:10"
    user: "$DOCKER_USER"
    working_dir: /home/node/client
    volumes:
      - ./app/client:/home/node/client
    environment:
      NODE_ENV: "development"
      SERVER_NAME_SERVER: ${SERVER_NAME_SERVER}
      SERVER_NAME_CLIENT: ${SERVER_NAME_CLIENT}
    ports:
      - "81:81"
    command: >
      bash -c "npm install
      && npm run serve"

  daemon:
    image: "node:10"
    user: "$DOCKER_USER"
    working_dir: /home/node/daemon
    volumes:
      - ./app/daemon:/home/node/daemon
    environment:
      NODE_ENV: "development"
      SERVER_NAME_SERVER: ${SERVER_NAME_SERVER}
      SERVER_NAME_CLIENT: ${SERVER_NAME_CLIENT}
    command: >
      bash -c "npm install
      && npm run start-daemon"

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/working:/etc/nginx/conf.d/
      - ./app/server:/var/server
      - ./volumes/server/logs:/var/log/nginx/server
      - ./volumes/client/logs:/var/log/nginx/client
    links:
      - client