version: '3'

services:
  php:
    restart: always
    build: docker/php
    env_file:
      - .env
    ports:
      - 10000
    volumes:
      - ./app/server:/var/server

  node:
    restart: always
    image: "node:10"
    user: "$DOCKER_USER"
    working_dir: /home/node/client
    volumes:
      - ./app/client:/home/node/client
    environment:
      NODE_ENV: "development"
      SERVER_NAME_SERVER: ${SERVER_NAME_SERVER}
      SERVER_NAME_CLIENT: ${SERVER_NAME_CLIENT}
    ports:
      - "8089:8089"
    command: >
      bash -c "npm install
      && npm run serve"
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/working:/etc/nginx/conf.d/
      - ./app/server:/var/server
      - ./volumes/server/logs:/var/log/nginx/server
      - ./volumes/client/logs:/var/log/nginx/client
    links:
      - php
      - node